services:
  mongodb:
    image: mongo:latest
    container_name: auth-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - auth-network

  # auth-service:
  #   build:
  #     context: ./.
  #     dockerfile: Dockerfile
  #   container_name: auth-service
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - auth-network
  #   environment:
  #     - MONGODB_URL=mongodb://mongodb:27017

networks:
  auth-network:
    driver: bridge

volumes:
  mongodb_data: